### ISSUE TITLE
Continued support?

### ISSUE THREAD

**Issue by Astevus** [schlangguru/valheim-mod-ship-marker#3]
Just wondering if you were going to update and continue support? I've updated for my personal use, and if you're not interested in maintaining it, I'd be happy to take it over (and provide all credits due). I'm the author of a number of Valheim mods, and for me, this one is indispensable.

**Comment by Astevus** [comment]
I haven't heard from you, so I'm posting a mod that includes your license and attributes the original work to you. I believe this is in accordance with the polices you've set. If you ever request it, I will remove the mod. I've updated for the recent Valheim updates and added Portals and map icon color configs. Take care and thanks for the great original work.

**Comment by schlangguru** [comment]
I have no intent to update this mod since I'm not playing Valheim at the moment. Feel free to use this code in any way you like. You can create a fork and maintain your version there if you'd like. Feel also free to publish your updated mod on NexusMods.
